# Usa una imagen base de MySQL
FROM mysql:latest

# Definir variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=admin01
ENV MYSQL_DATABASE=BASE-01A
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Puerto por defecto de MySQL
EXPOSE 3306

# Comando para ejecutar al iniciar el contenedor
CMD ["mysqld"]
