# Use the official MySQL image
FROM mysql:8.0

# Set the root password for MySQL
ENV MYSQL_ROOT_PASSWORD=example

# Create a database
ENV MYSQL_DATABASE=mydatabase

# Copy the SQL scripts to initialize the database
COPY ./MySQL/create_table.sql /docker-entrypoint-initdb.d/
